name: Benutzerauthentifizierung Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install


    - name: Start application
      run: |
        nohup npm start &
        sleep 50
    - name: Check if server is running
      run: curl -I http://localhost:3000 

    - uses: matt-ball/newman-action@master
      with:
        collection: ./Postman/benutzerauth.postman_collection.json

    - name: Stop application
      run: |
        pkill node 