name: Benutzerauthentifizierung Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install


    - name: Start application
      run: |
        nohup npm start &
        sleep 10

    - name: Run Postman tests with Newman
      run: |
        npx newman run postman/benutzerauth_postman_collection.json \
          --delay-request 500
      timeout-minutes: 2 

    - name: Stop application
      run: |
        pkill node 